### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mayankn792** [rajatomar788/pywebcopy#1]
Exception has occurred: pywebcopy.exceptions.AccessError
Access to https://www.odoo.com/forum/help-1/question/odoo-9-show-user-popups-95514 not allowed by site.

this exception has occurred when i am trying to run following script

from pywebcopy.core import save_webpage

save_webpage(url='https://www.odoo.com/forum/help-1/question/odoo-9-show-user-popups-95514',mirrors_dir='C:/')

**Comment by rajatomar788** [comment]
Hey bro,
The error says it all, the webpage doesnot permit you to scrap the webpage.
You can bypass that by adding one more argument to the save_webpage call

Ex.
save_webpage (
#...your url etc.
,
bypass_robots=True
)

**Comment by mayankn792** [comment]
DONE 

but when i am trying to download web-pages from [archive.org](https://web.archive.org), **.html** is file is not downloading

here is code
`from pywebcopy.core import save_webpage
save_webpage(url='http://web.archive.org/web/19970126045828/http://www.archive.org',mirrors_dir='Saved_Pages',bypass_robots=True)`

**Comment by rajatomar788** [comment]
First your url is either pasted here wrong or is wrong.
second can you post a traceback, so that i can inspect the issue.

**Comment by mayankn792** [comment]
Thanks

my url was wrong
