### ISSUE TITLE
ImportError: cannot import name 'save_website' from 'pywebcopy'

### ISSUE THREAD

**Issue by serranoarevalo** [rajatomar788/pywebcopy#10]
Just running the example from the README throws an error

![code](https://user-images.githubusercontent.com/3612017/58393418-97577480-8079-11e9-968c-40e8f2100f4d.png)

```ImportError: cannot import name 'save_website' from 'pywebcopy'```

**Comment by rajatomar788** [comment]
Try directly importing it from module like this

from pywebcopy.apis import save_webpage

Btw which color scheme is that :)

**Comment by serranoarevalo** [comment]
I'm using a different tool now, thanks!

https://material-theme.site/

That's the color scheme.
