### ISSUE TITLE
Fails on tel links

### ISSUE THREAD

**Issue by totalhack** [rajatomar788/pywebcopy#107]
It's trying to parse telephone links as html page/resource links.

```
lib/python3.9/site-packages/pywebcopy/urls.py", line 231, in parse_url
    raise LocationParseError(url)
pywebcopy.urls.LocationParseError: tel:+[REDACTED]
```

**Comment by rajatomar788** [comment]
It should not fail as there was a patch on github sometimes back. Jave you tried using the code from github?

**Comment by totalhack** [comment]
I used the latest version from pip. Should that not have the patch?

**Comment by totalhack** [comment]
The latest release in git is 7.0.1, I have 7.0.2. Does that not have the fix?

**Comment by rajatomar788** [comment]
No, but I should release a patch tommorow

**Comment by totalhack** [comment]
I see you merged a fix -- do you plan on pushing a new version to pip?

**Comment by rajatomar788** [comment]
I am afraid it won't be any time soon.
