### ISSUE TITLE
cannot import name url2pathname

### ISSUE THREAD

**Issue by human39** [rajatomar788/pywebcopy#16]
OS: Ubuntu 18.04.3 LTS
Python: Python 2.7.15+

I have installed pywebcopy via pip on a new install on ubuntu and I'm getting the following error:

```
~# python -m pywebcopy
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/pywebcopy/__init__.py", line 34, in <module>
    from .configs import config, SESSION
  File "/usr/local/lib/python2.7/dist-packages/pywebcopy/configs.py", line 16, in <module>
    from .compat import urlparse, urljoin
  File "/usr/local/lib/python2.7/dist-packages/pywebcopy/compat.py", line 30, in <module>
    from urlparse import urlparse, urlunparse, urljoin, urlsplit, urldefrag, url2pathname, pathname2url
ImportError: cannot import name url2pathname
```
I'm fairly certain that urlparse is a standard module, so I'm not totally sure why url2pathname cannot be be imported.  Suggestions?

**Comment by rajatomar788** [comment]
There must some be issue with the python standard library. You should try
reinstalling it.

**Comment by human39** [comment]
Thanks!  I'll try it.. my first attempts ie. `apt install --reinstall libpython2.7-stdlib` have not worked.  I'll report back.

**Comment by jmesa** [comment]
url2pathname, pathname2url are part of urllib:
https://docs.python.org/2/library/urllib.html
https://docs.python.org/2/library/urlparse.html

Maybe, this is the problem we are facing using Python2.

**Comment by rajatomar788** [comment]
Which pywebcopy version are you using?

**Comment by rajatomar788** [comment]
If its 4 or less, then you should upgrade it to 6.

**Comment by rajatomar788** [comment]
Problem could be a compatibility issue, because urlparse modules are
located at different location in python 2 than compared to python 3.

**Comment by jmesa** [comment]
I am using v6:
$ pip2 show pywebcopy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7. More
details about Python 2 support in pip, can be found at
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Name: pywebcopy
Version: 6.0.0
Summary: Python package for cloning complete webpages and websites to local
storage.
Home-page: https://github.com/rajatomar788/pywebcopy/
Author: Raja Tomar
Author-email: rajatomar788@gmail.com
License: Apache License 2.0
Location: /usr/lib/python2.7/site-packages
Requires: w3lib, pyquery, requests, parse, lxml, fire, bs4
Required-by:

Thanks for your fast response.

**Comment by rajatomar788** [comment]
Issue has been solved. I am closing this.

**Comment by rajatomar788** [comment]
Thank you jmesa!
