### ISSUE TITLE
CSS images are not downloaded

### ISSUE THREAD

**Issue by matthijsb** [rajatomar788/pywebcopy#19]
Hi cool project, works very well, i just noticed one small bug when it tries to download css linked files:

css:
background-image: url('../img/email.png');

Error when downloading the image:

(Pdb) req
<Response [403]>

(Pdb) req.url
"/img/email.png'"

(Pdb) bt
  /pywebcopy/elements.py(341)run()
-> f.run()
  /pywebcopy/elements.py(56)run()
-> self.download_file()
> /pywebcopy/elements.py(110)download_file()
-> LOGGER.error(

saved / transformed css:
background-image: url(../img/35e3b271__email.png%27);

Seems the parsing of url() calls in css dont anticipate for '' strings?

**Comment by matthijsb** [comment]
I think it should be fixed if you replace these regexes in globals.py:

#https://www.regextester.com/106463
#CSS_URLS_RE = re.compile(b'''url\\(['"]?([^)]*)["']?\\)''', re.I)
CSS_URLS_RE =  re.compile(b'''url\\((?!['"]?(?:https?:|\/\/))(['"]?)([^'")]*)\\1\\)''', re.I)

#https://regex101.com/r/lC1hO3/2
#CSS_IMPORTS_RE = re.compile(b'''@import\\s*['"](.*?)['"]\\s*''', re.I)
CSS_IMPORTS_RE =  re.compile(b'''@import.*?["']([^"']+)["'].*?''', re.I)

CSS_FILES_RE = re.compile(b'''(?:url\\((?!['"]?(?:https?:|\/\/))(['"]?)([^'")]*)\\1\\))|(?:@import.*?["']([^"']+)["'].*?)''', re.I)

**Comment by rajatomar788** [comment]
They are not working!!?

**Comment by matthijsb** [comment]
Strange, they seem to work for me, do you have an example site you tested them on where they dont work?

**Comment by rajatomar788** [comment]
Try bootstrap.css

**Comment by matthijsb** [comment]
Ah forgot to mention i also changed LinkTag.repl:
url = match_obj.group(1)
to:
url = match_obj.group(2)

**Comment by rajatomar788** [comment]
what was the page url?
Is is working now or a fix is required?

**Comment by rajatomar788** [comment]
This issue has been fixed in the release 6.1.0.
