### ISSUE TITLE
config.setup_config hangs for specific url

### ISSUE THREAD

**Issue by youngblood** [rajatomar788/pywebcopy#22]
problematic url = 'http://www.mcclatchydc.com/opinion/article24604315.html'

CODE I'm using (which seems to work with most other urls):
>>> url = 'http://www.mcclatchydc.com/opinion/article24604315.html'
>>> config.setup_config(url,
...                     project_name=str(hash(url)),
...                     project_folder=base_dir_txt, bypass_robots=True, over_write=False, debug=True)

OUTPUT:
pywebcopy.configs - DEBUG    - {'debug': True, 'log_file': '/Users/reed/Downloads/scraped_content/-4279476708681949691/pywebcopy_log.log', 'project_name': '-4279476708681949691', 'project_folder': '/Users/reed/Downloads/scraped_content/-4279476708681949691', 'over_write': False, 'bypass_robots': True, 'zip_project_folder': True, 'delete_project_folder': False, 'allowed_file_ext': ['.html', '.php', '.asp', '.aspx', '.htm', '.xhtml', '.css', '.json', '.js', '.xml', '.svg', '.gif', '.ico', '.jpeg', '.pdf', '.jpg', '.png', '.ttf', '.eot', '.otf', '.woff', '.woff2', '.pwcf'], 'http_headers': {'Accept-Language': 'en-US,en;q=0.9', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 PyWebCopyBot/6.1.1'}, 'load_css': True, 'load_javascript': True, 'load_images': True, 'join_timeout': None, 'project_url': 'http://www.mcclatchydc.com/opinion/article24604315.html'}
urllib3.connectionpool - DEBUG    - Starting new HTTP connection (1): www.mcclatchydc.com:80

That's it - it just hangs there and never finishes executing that command.

**Comment by rajatomar788** [comment]
It could server side error. Maybe try upgrading all the libraries
especially "requests".
