### ISSUE TITLE
how to change user agent?

### ISSUE THREAD

**Issue by marshonhuckleberry** [rajatomar788/pywebcopy#29]
how to change user agent?

**Comment by rajatomar788** [comment]
The pywebcopy uses a inbuilt [`requests`](https://2.python-requests.org/en/master/) library session which stores the
headers and cookies and all other data during all the requests.
You can customize this session before start to modify the user-agent or cookies or
headers etc.

```python
import pywebcopy 

pywebcopy.SESSION.headers['User-Agent'] = "your-custom-useragent"

pywebcopy.config.setup_config('http://google.com',  '/path/to/downloads/', debug=True)
pywebcopy.save_webpage('http://google.com')

```

You can learn more about manipulation of `requests` session from documentation.

[https://2.python-requests.org/en/master/user/advanced/](https://2.python-requests.org/en/master/user/advanced/)
