### ISSUE TITLE
File ext '' is not allowed for file at

### ISSUE THREAD

**Issue by aviraonepiece** [rajatomar788/pywebcopy#3]
`#!/usr/bin/python
# -*- coding:utf-8 -*-

from pywebcopy import WebPage

url = 'http://baijiahao.baidu.com/s?id=1622464741855375146'
project_loc = 'C:/Users/康康/Desktop'

wp = WebPage(url,
project_folder=project_loc,
default_encoding=None,
HTML=None,
bypass_robots=True
)

wp.save_complete()`

i  got   CRITICAL - pywebcopy.core.new_file:189 - File ext '' is not allowed for file at 'http://t10.baidu.com/it/u=788283957,2664293696&fm=173&app=49&f=JPEG?w=528&h=446&s=27C8D010495E60CC40E4045A0300C0F2'

but  i have set  bypass_robots

**Comment by rajatomar788** [comment]
Hey!
It's working fine.
Its just not recognizing the file type of a dynamicly generated image which
is hard in real.

There is no relation between bypass_robots and file type not being
recognized.

But I will definitely write a patch in future with better support for
dynamic files.

Thank you..
