### ISSUE TITLE
how to use cookies?

### ISSUE THREAD

**Issue by marshonhuckleberry** [rajatomar788/pywebcopy#30]
how to use cookies same as a browser would do, the cookies are saved automaticaly and no manual copy needed?

**Comment by marshonhuckleberry** [comment]
forgot to say, i use python 3.6

**Comment by rajatomar788** [comment]
The pywebcopy uses a inbuilt [`requests`](https://www.dev2qa.com/how-to-get-set-http-headers-cookies-and-manage-sessions-use-python-requests-module/) library session which stores the
headers and cookies and all other data during all the requests.
You can customize this session before start to modify the cookies or
headers etc.

```python
import pywebcopy 

pywebcopy.SESSION.cookies['cookie_key'] = 'some_id'

pywebcopy.config.setup_config('http://google.com',  '/path/to/downloads/', debug=True)
pywebcopy.save_webpage('http://google.com')
```

You can learn more about manipulation of requests session from documentation.

[https://www.dev2qa.com/how-to-get-set-http-headers-cookies-and-manage-sessions-use-python-requests-module/](https://www.dev2qa.com/how-to-get-set-http-headers-cookies-and-manage-sessions-use-python-requests-module/)

**Comment by marshonhuckleberry** [comment]
what is this part of the code doing? 
pywebcopy.config.setup_config('http://google.com',  '/path/to/downloads/', debug=True)

**Comment by marshonhuckleberry** [comment]
it looks like its the config but im confused why use url two times? 
pywebcopy.config.setup_config('**http://google.com**'
pywebcopy.save_webpage('**http://google.com**')

**Comment by rajatomar788** [comment]
This lib was part of a bigger project, hence the global config.
I don't want have enough free time or clear mind to rewrite the code.
Maybe in future or maybe not.

**Comment by rajatomar788** [comment]
The `url` value in the `pywebcopy.config.setup_config` is used for setup purposes. 
The config handlers loads `robots.txt` from this url and also it prepares the base path based roughly on the url where all the files will end up. 

But in the second case the url is used to load page itself from the server. 

So bottom line is they both are required. You should just store the url in a variable and just pass it twice.

**Comment by marshonhuckleberry** [comment]
from what i can understand from requests documentation and google is that there are two ways of using cookies:
1. manually set cookies and send them  (a function called post or something)
2. automaticaly set cookies like in a browser (a function called session() or something)
however requests documentation lacks usefull examples wich shows that two ways of using cookies, most important, also testing cookies not easy, maybe test on facebook login, anyway trying to understand those things seems like a big big waste of time with no results

**Comment by marshonhuckleberry** [comment]
and i forgot to say is not just complicated to set cookies in requests but is 1000 complicated to set cookies in pywebcopy

**Comment by rajatomar788** [comment]
Cookies are automatically stores in the pywebcopy.SESSION attribute which
is essentially a requests.Session() object.
If you can do it on requests then you can do it on pywebcopy. There is
absolutely no difference. Btw requests is a very well known library in
Python .
You can find hundreds of ways to authenticate through requests on
stackoverflow.

**Comment by rajatomar788** [comment]
If you still have issue then use a third party library `MechanicalSoup` for browser navigation and form filling in python then use that library session to set it as `pywebcopy.SESSION`. It will be smooth.
I am now closing this issue if you have any further problems then you can always reopen this issue.
