### ISSUE TITLE
program download method

### ISSUE THREAD

**Issue by marshonhuckleberry** [rajatomar788/pywebcopy#31]
will the program check if the file already exists or it will download it anyway and if it exists it will replace it? its very important thing because it affects scraping time, bandwidth resource usage and spider detection, some websites detect if you scrape them if you download same files again and again

**Comment by marshonhuckleberry** [comment]
is good to keep low profile when scraping also wanted to ask about adding delays after each downloaded link to avoid detection

**Comment by rajatomar788** [comment]
Yes. it could be implemented easily by overridding the get method of
session.

**Comment by rajatomar788** [comment]
Yes it checks for existence  and only downloads only if missing. You can force it to download a file everytime it sees a link by adding `over_write=True` to global config .

**Comment by rajatomar788** [comment]
Delays could be implemented easily by overridding the get method of
session.
