### ISSUE TITLE
ImportError: cannot import name UserDict

### ISSUE THREAD

**Issue by Z-Zen** [rajatomar788/pywebcopy#40]
I encountered an issue today while trying to import `pywebcopy`. This is related to the[ closed issue ](https://github.com/rajatomar788/pywebcopy/issues/25). I tried to install via `pip` and also building it manually by cloning from github.

```
Traceback (most recent call last):
  File "test_untitled2.py", line 13, in <module>
    from pywebcopy import save_webpage
  File "/usr/local/lib/python2.7/dist-packages/pywebcopy/__init__.py", line 49, in <module>
    from .configs import config, SESSION
  File "/usr/local/lib/python2.7/dist-packages/pywebcopy/configs.py", line 13, in <module>
    from collections import UserDict
ImportError: cannot import name UserDict
```

Any idea what could be the problem ?

Thanks in advance.

**Comment by rajatomar788** [comment]
The UserDict is not available in python2. It is fixed on the repo but not released on pypi.
See #25

**Comment by rajatomar788** [comment]
New version 6.2.0 is now released on pypi. Install it using pip:
```shell
$ pip install pywebcopy==6.2.0
```

If you still have any problems then reopen this issue.
