### ISSUE TITLE
Process hanging

### ISSUE THREAD

**Issue by maxpearl** [rajatomar788/pywebcopy#5]
I'm working to mirror a whole site, and it seems to be going fine, but then it just hangs, basically forever (I left it overnight, but it was still hanging.) 

It doesn't leave a message, it just hangs.

When I interrupt by keyboard, it stops here: 
```
File "/usr/local/src/mirror/otf_mirror/.venv/lib/python3.6/site-packages/pywebcopy/crawler.py", line 128, in run
    D_QUEUE.join()              # Wait for the download queue to be emptied
```
Is there anyway to know: 
1) how big the queue is
2) is it actually getting smaller?

When it is running, the process is using pretty much all of the CPU of the VPS I have, plus about 35% of the memory, but when it's hanging, it drops down to 2%

Is there a way to perhaps tweak the speed so that the queue doesn't get overloaded?

I'm going to try to increase the capacity of my VPS to see if that helps.

**Comment by rajatomar788** [comment]
Hey Max,
This issue happens sometimes as crawler tries to get a page from a dead server.
So, to fix this issue i am working on a brand new version 6 which will be more faster and error free when
finished.
If you want I can provide the current stage of it to you for testing or suggestion if you want.

**Comment by maxpearl** [comment]
The server I'm grabbing from is definitely not dead - although certainly there might be a dead link.  (We're doing purposeful mirroring of sites we are connected to.)

I'm happy to test - can you make a new branch here with your new version, so I can test?

**Comment by rajatomar788** [comment]
check the BETA branch I just created.

**Comment by rajatomar788** [comment]
The documentation has some things to fix in it. But overall apis are I think working.
