### ISSUE TITLE
Relative links

### ISSUE THREAD

**Issue by danielfaulknor** [rajatomar788/pywebcopy#52]
I'm trying to download a webpage where the links are relative (for example an href may point to `main/` where it's actually `[site being crawled]/folder/main` but we lose the `/folder` bit. Is there a way to append the parent URL?

**Comment by rajatomar788** [comment]
can you give more details? paste the log from the console.

the library tries to recreate the structure reported by the site. So the bits should not be missing.

**Comment by danielfaulknor** [comment]
Apologies, it looks like an issue on my end
