### ISSUE TITLE
Hangs in involuntary places. Using a basic example.

### ISSUE THREAD

**Issue by Salim9304** [rajatomar788/pywebcopy#54]
1) pip3 install pywebcopy
2) from pywebcopy import save_webpage

kwargs = {'project_name': 'some-fancy-name'}

save_webpage(
    url='https://fantlab.ru/',
    project_folder='downloads',
    **kwargs
)
3) Hangs either on js or on saving icons.

OS GNU/LInux Debian.
python 3.7

**Comment by rajatomar788** [comment]
You should take a look at #46 for more discussions.
