### ISSUE TITLE
Script not completed

### ISSUE THREAD

**Issue by bralbral** [rajatomar788/pywebcopy#57]
Hey! this is my code: 
```

import pywebcopy
url = 'https://habr.com/ru/post/203012/'
kwargs = {}
project_folder = 'download'
project_name = 'habr'
logfile = 'log_file.log'
# You should always start with setting up the config or use apis
pywebcopy.config.setup_config(url, project_folder, project_name, log_file=logfile, **kwargs)
wp = pywebcopy.WebPage()
wp.get(url)
#wp.save_complete()
wp.save_html()
wp.save_assets()
```

Threads get stuck after scrapping. How can I exit the script in the usual way?
![image](https://user-images.githubusercontent.com/54455457/91435755-7f1f6800-e86f-11ea-8c02-26ccfa6b71b2.png)

**Comment by rajatomar788** [comment]
Did you read the issue #46 before opening this thread?

**Comment by bralbral** [comment]
No,  i did not sorry.  So the problem hasn't been solved in any way?
