### ISSUE TITLE
Path is on mount S: start on mount C:

### ISSUE THREAD

**Issue by bobsburgers** [rajatomar788/pywebcopy#58]
windows 10 pro python 3.7.8
just the one site "https://breakingnewscentral.com/" seems to have this issue. 

With either paths 'Downloads/this_dumb_thing' or 'C:/Users/guy/Downloads/this_dumb_thing'

currently i used this 
`def scrape(url, folder, timeout=1):
	config.setup_config(url, folder)
	
	wp = WebPage()
	wp.get(url)
	
	# start the saving process
	wp.save_complete()
	
	# join the sub threads
	for t in wp._threads:
		if t.is_alive():
			t.join(timeout)
	
	# location of the html file written
	return wp.file_path`

before i just used example code and got the same thing 

`kwargs = {'project_name': 'thedetrend'}
	save_webpage(
		
		# url pf the website
		url=url,
		
		# folder where the copy will be saved
		project_folder=folder,
		**kwargs
	)`

**Comment by rajatomar788** [comment]
Try a different drive path, make sure its an absolute path ending with forward slash.

**Comment by nxvinh222** [comment]
> Try a different drive path, make sure its an absolute path ending with forward slash.

can you give an example please

**Comment by rajatomar788** [comment]
@nxvinh222 see #14

**Comment by nxvinh222** [comment]
> @nxvinh222 see #14

tks i did it
