### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by athesh-pargau7** [rajatomar788/pywebcopy#61]
In bypass robots statements it shows me error @rajatomar788  since i assigned true!!
bypass_robots=True
TypeError: unsupported operand type(s) for ** or pow(): 'bool' and 'dict'

**Comment by rajatomar788** [comment]
It shouldn't be happening. Try ```
bypass_robots="True"
```

**Comment by athesh-pargau7** [comment]
It again shows error @rajatomar788 
 bypass_robots="True"
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'dict'

instead of bool,it shows string!

**Comment by rajatomar788** [comment]
Paste the entire code you are running. Along with the log if ok.

**Comment by athesh-pargau7** [comment]
def website_cloner(): 	#website cloning part
	
	website_url=input("Enter the website URL: ")
	name=input("Enter the folder name: ")
	path=input("Enter the path to save the files: ")
	
	kwargs = {'project_name': name}

	save_webpage(

    	# url pf the website
    	url=website_url,

    	# folder where the copy will be saved
    	project_folder=path,
    	bypass_robots="True"
    	#
    	**kwargs
	)

website_cloner()

**Comment by rajatomar788** [comment]
Bypass_robots takes a bool as its value from now on.

`bypass_robots=True`
