### ISSUE TITLE
How to fill a form login

### ISSUE THREAD

**Issue by mayouf** [rajatomar788/pywebcopy#7]
Hi Rajatomar,

Would you please indicate how to login a website OR what class or function should we amend to implement this feature

**Comment by rajatomar788** [comment]
Hey,
The pywebcopy uses a inbuilt "requests" library session which stores the
cookies and all other data during all the requests.
You can customize this session before start to modify the cookies or
headers etc.

import pywebcopy

pywebcopy.SESSION.headers.update(auth={"username": "password"})

pywebcopy.config.setup_config(...)
pywebcopy.save_webpage(...)


You can learn more about requests Session here:
1.
https://stackoverflow.com/questions/31554771/how-to-use-cookies-in-python-requests
2. https://2.python-requests.org/en/master/user/quickstart/
