### ISSUE TITLE
same domain pdf links wrapped by anchor tag is skipped

### ISSUE THREAD

**Issue by NickVeld** [rajatomar788/pywebcopy#74]
Because of:
```
class AnchorTag(NullTag):
    """Anchor tag does nothing.
    Otherwise it will go on a infinite websites download spree.
    """
```

**Comment by rajatomar788** [comment]
Pdf links can be without extension also. Which makes it unnecessary to add checks.

**Comment by NickVeld** [comment]
In my case there are links with extension inside <a> and I forced them to be processed as TagBase

**Comment by NickVeld** [comment]
Fixed in https://github.com/rajatomar788/pywebcopy/pull/75
