### ISSUE TITLE
[Python 3.10] TypeError: multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by jaraco** [rajatomar788/pywebcopy#90]
Attempting to import the module on Python 3.10 results in this error:

```
~ $ python3.10 -m pip-run -q --use-pep517 pywebcopy -- -c "import pywebcopy"
WARNING: You are using pip version 21.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-6toqwjfg/pywebcopy/__init__.py", line 49, in <module>
    from .configs import config, SESSION
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-6toqwjfg/pywebcopy/configs.py", line 18, in <module>
    from .exceptions import AccessError
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-6toqwjfg/pywebcopy/exceptions.py", line 46, in <module>
    class UrlTransformerNotSetup(PywebcopyError, UnboundLocalError):
TypeError: multiple bases have instance lay-out conflict
```

Importing on Python 3.9 works fine.

**Comment by rajatomar788** [comment]
Fixed in version 7.

**Comment by oldborrow** [comment]
Hello friend, could you please explain what did you mean by _Fixed in version 7._? I'm having same trouble here and can't find a way to fix it

**Comment by jaraco** [comment]
Are there any plans to release version 7? Other users are encountering this issue. It doesn't help much to have a fix that isn't released.

**Comment by rajatomar788** [comment]
Version 7 will be released in 15 days top.

Having a fix doesn't mean that it is compatible with the existing code base.

It will be released as soon as possible, mind the bugs.

**Comment by sTiKyt** [comment]
![image](https://user-images.githubusercontent.com/35602029/200180349-61535343-581e-40cd-b02a-4a44a29dd9e5.png)
