### ISSUE TITLE
Module not found 'CacheControl'

### ISSUE THREAD

**Issue by sudocpMATHdotPY** [rajatomar788/pywebcopy#96]
Is Replit incompatible with this module? I tried using it and it decided that 'CacheControl' no longer existed. When I installed CacheControl manually, it still insisted that it did not exist. This is the only module I have had this problem with

**Comment by sudocpMATHdotPY** [comment]
I tried it again and it started saying 'called the underlying ``raw`` object must not be accessed again. (line 960)'

**Comment by BrandonKMLee** [comment]
What could be the cause of this then?

**Comment by rajatomar788** [comment]
@BrandonKMLee the cause is the discountinuation of the cache-control library.

**Comment by BrandonKMLee** [comment]
I meant that are there any other Cache libraries that can replace it, or was it unnecessary?

**Comment by rajatomar788** [comment]
@BrandonKMLee you could still download the library and make it work. It wasn't unnecessary, just that it got discontinued.
